### ISSUE TITLE
Align Find-VSCodeExtension default behaviour with similar commands

### ISSUE THREAD

**Issue by janegilring** [gerane/VSCodeExtensions#1]
Would it make sense to make Find-VSCodeExtension output the same  as Find-VSCodeExtension -WildCard -ExtensionName \* in order to align with the behaviour of similar commands such as Find-Module?

**Comment by gerane** [comment]
I have been thinking about this, I am wanting to add more functionality to this command and add the ability to search by publisher, tags, categories and other properties of the extensions. So I decided to leave the wildcards portion in as is until I figured out exactly what other search capabilities i wanted.

I agree and want to move to this sort of functionality. I was wanting to look at the actual code behind find-module and see how out handles it's wildcards. 

If you have suggestions if love to hear them.

There is also probably some opportunities to create searches for things like, top trending downloads for the day, week or month. Something like this might deserve it's own command. This is essentially the same data the VSCode gallery is using for their little categories on the main page.

**Comment by gerane** [comment]
So, I need to look into this a bit more. It actually looks like Find-Module isn't properly handling wildcards. If you run Get-Help, it states it does not support wildcards and it only supports "*" and not "?" or ranges for "[a-c]"

This like shows that cmdlets should support wildcards this way.

https://msdn.microsoft.com/en-us/library/aa717088%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

It looks like where-object -like properly supports the wildcards though, so I will just go that route. Should simplify the code a great deal.

**Comment by gerane** [comment]
I just pushed some changes to the Dev branch. If you want to take a look. I need to test it a bit more, and will start writing some Pester tests tomorrow evening or this weekend. Normally don't wait this long to write tests, but given the nature of the module, and some factors being out of my control, I wanted to wait.

Fixes #1: Added Wildcard, category, and tag support. Fixed Help.
- Dropped FullName Parameter in favor of a PublisherName one. Accepts WildCards.
- Added Tag parameter for filtering by Tags. Accepts WildCards
- Added Category paramter for filtering by categories. Has a validate set for possible names.
- Fixed External Help
- Fixed a typo in the Install-VSCodeExtension that might cause an extension to be installed if already installed.
- Dropped the Wildcard parameter in favor of supporting it by default similar to Find-Module.

**Comment by janegilring** [comment]
Looks great!

Although, running Find-VSCodeExtension without any parameters prompts for a value for -ExtensionName. Maybe it could be assigned a default value of \* and not be marked as mandatory in order to align completely with Find-Module?
